# Filepaths
filepaths:
  data_spreadsheet:
  final_document:
  document_template:

# Excel Settings
excel:
  standard_column:
  rfi_column:
  sheet_name:
  advanced:
    row_shift: 3
    header: 1
    ignore_color: "FF00B050"
