# Filepaths
filepaths:
  data_spreadsheet: "./files/input.xlsx"
  document_template: "./files/template.docx"
  final_document: "./files/completed_review.docx"

# Excel Settings
excel:
  standard_column: "C"
  rfi_column: "K"
  sheet_name: "FINAL verification"
  advanced:
    row_shift: 3
    header: 1
    ignore_color: "FF00B050"


